name: Test Setup Machine Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Run once per week on Sunday at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Test Setup Machine Script
      run: |
        chmod +x test_setup_machine.sh
        ./test_setup_machine.sh
